# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 05:29
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_purchaseorderline_line_revise_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_type', models.CharField(blank=True, max_length=255)),
                ('res_type_class', models.CharField(blank=True, max_length=255)),
                ('agency_ref_num', models.CharField(blank=True, max_length=255)),
                ('res_emp_num', models.CharField(blank=True, max_length=255)),
                ('res_full_name', models.CharField(blank=True, max_length=255)),
                ('date_of_join', models.DateField(blank=True, null=True)),
                ('po_position', models.CharField(blank=True, max_length=255)),
                ('po_level', models.CharField(blank=True, max_length=255)),
                ('division', models.CharField(blank=True, max_length=255)),
                ('section', models.CharField(blank=True, max_length=255)),
                ('manager', models.CharField(blank=True, max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('capex_percent', models.IntegerField(default=0)),
                ('capex_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('opex_percent', models.IntegerField(default=0)),
                ('opex_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('revenue_percent', models.IntegerField(default=0)),
                ('revenue_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('remarks', models.TextField(blank=True)),
                ('po_num', models.CharField(blank=True, max_length=255)),
                ('po_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('capex_commitment_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('opex_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('revenue_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('contractor', models.CharField(blank=True, max_length=255)),
                ('po', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PurchaseOrder')),
                ('po_line_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PurchaseOrderLineDetail')),
            ],
        ),
    ]
