# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='po_os_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
