# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 05:52
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_unitprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_hour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('invoice_claim', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('invoice_cert_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('remarks', models.TextField(blank=True)),
                ('po_line_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PurchaseOrderLineDetail')),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Resource')),
            ],
        ),
    ]
