# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 12:04
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_purchaseorderlinedetail_rate_diff_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='grade_level',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='po_rate_percent_increase',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='res_job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
