# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160817_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='has_tool_or_uniform',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
